import NewsButton from "./newsButton";
import snapScroll from "./snapScroll";
import timeLine from "./timeLine";
import Hamburger from "./hamburger";
import LanguageSelector from "./languageSelector";
Hamburger();
LanguageSelector();
NewsButton();
snapScroll();
timeLine();
