<?php if (function_exists('acf_add_local_field_group')) :

    acf_add_local_field_group(array(
        'key' => 'group_5e8b1f5d21d2d',
        'title' => 'About',
        'fields' => array(
            array(
                'key' => 'field_5e8b20a52b19a',
                'label' => 'Hero image',
                'name' => 'hero_image',
                'type' => 'image',
                'instructions' => 'This is the image which will be shown on the top part of the page',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'large',
                'library' => 'all',
                'min_width' => 1024,
                'min_height' => 1024,
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5e8b21f72b19b',
                'label' => 'Hero title',
                'name' => 'hero_title',
                'type' => 'text',
                'instructions' => 'This is the title of the page',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Om huset och verksamheten',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5e8b22592b19c',
                'label' => 'Subheading 1',
                'name' => 'subheading_1',
                'type' => 'text',
                'instructions' => 'This is the heading for the first paragraph',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Att levandegöra vårt kulturarv genom konsten',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5e8b24112b19d',
                'label' => 'Paragraph 1',
                'name' => 'paragraph_1',
                'type' => 'textarea',
                'instructions' => 'This is the first paragraph',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'En grundtanke med verksamheten i Gathenhielmska Huset är att skapa processer som uppmuntrar innovativa möten och samverkan mellan konstnärer, kulturutövare, lokalt näringsliv och besökare. Gathenhielmska Huset skall vara en sammanlänkande plats i området och en arbetsplats och scen för design, dans, opera, musik, teater, konst och litteratur, med mera

Genom att att arrangera föreställningar, visningar, kurser och andra evenemang skapar vi inte bara ett program för att tillgängliggöra huset och dess kulturhistoriska värde men också ett sammanhang för nutidens kulturaktörer. Vi sätter platsen, artister och besökarna i centrum för Stigbergstorgets framtida utveckling. Dessa möten på en sådan unik plats inspirerar till att hitta och tro på nya former och möjligheter för olika typer av samarbeten, vilket gynnar samhället. Därför tror vi att Gathenhielmska Huset kommer att vara ett viktigt kulturellt nav i Göteborg, en plattform som kommer att belysa processer som bidrar till samhällsutveckling och lokal tillväxt. Detta är inte en hypotes utan har redan påverkat områdets utveckling rejält.

En metafor för detta arbete är Skeppet. Om Gathenhielmska Huset är ett skepp så är vi på färd - mot hamnar och horisonter, för att skapa utbyten och förbindelser för konst och kultur. Men Gathenhielmska Huset är också en hamn - en sammanlänkande plats och ett nav för det fria kulturlivets utveckling.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 10,
                'new_lines' => '',
            ),
            array(
                'key' => 'field_5e8b25602b19e',
                'label' => 'Subheading 2',
                'name' => 'subheading_2',
                'type' => 'text',
                'instructions' => 'This is the second subheading',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Arbetsplatser och intern samverkan',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5e8b25a22b19f',
                'label' => 'Paragraph 2',
                'name' => 'paragraph_2',
                'type' => 'textarea',
                'instructions' => 'This is the second paragraph',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Idag är det runt tio aktörer som arbetar regelbundet i huset. Allt från design, teater, musik, och casting, till arkitektur, samtalsterapi och Podcasts.

Vi är måna om att skapa skapa ett hållbart system för samverkan mellan olika aktörer. Vi tror att mångfalden gynnar både de som arbetar i huset och verksamheten i sin helhet. Olikheterna stärker en gemenskap där alla deltar utifrån sina förutsättningar. Varje aktör är en tillgång och en viktig del för helheten. Vi erbjuder en inkluderande och inspirerande miljö där alla är inbjudna att skapa eller ta del av skapandet och öppnar en plats utan begränsningar för mötet mellan historia, människa och konst.

Vi ser livet i och kring huset som ekosystem, en god grund för en samverkansmodell där vi tillsammans skapar en näringsrik mylla för samskapande, genom att verka för en hållbar och kollektiv gemenskap. Vi tror att en hållbar kollektiv social struktur, där vi stödjer och lär av varandra, är det bästa sättet att skapa ett sammanhang som kan förvalta Gathenhielmska husets värde.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 10,
                'new_lines' => '',
            ),
            array(
                'key' => 'field_5e8b272e2b1a0',
                'label' => 'Occupations heading',
                'name' => 'occupations_heading',
                'type' => 'text',
                'instructions' => 'Heading for occupations in the house',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Verksamheter i huset',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5e8b27d12b1a1',
                'label' => 'Occupations paragraph',
                'name' => 'occupations_paragraph',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Idag är det runt tio aktörer som arbetar regelbundet i huset. Allt från design, teater, musik, och casting, till arkitektur, samtalsterapi och podcasts.
Vi är måna om att skapa skapa ett hållbart system för samverkan mellan olika aktörer. Vi tror att mångfalden gynnar både de som arbetar i huset och verksamheten i sin helhet. Olikheterna stärker en gemenskap där alla deltar utifrån sina förutsättningar. Varje aktör är en tillgång och en viktig del för helheten. Vi erbjuder en inkluderande och inspirerande miljö där alla är inbjudna att skapa eller ta del av skapandet och öppnar en plats utan begränsningar för mötet mellan historia, människa och konst.

Vi ser livet i och kring huset som ekosystem, en god grund för en samverkansmodell där vi tillsammans skapar en näringsrik mylla för samskapande, genom att verka för en hållbar och kollektiv gemenskap. Vi tror att en hållbar kollektiv social struktur, där vi stödjer och lär av varandra, är det bästa sättet att skapa ett sammanhang som kan förvalta Gathenhielmska husets värde.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 10,
                'new_lines' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-templates/about.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'featured_image',
        ),
        'active' => true,
        'description' => '',
    ));

endif;
